version: '3'

vars:
  PYTHON: python3.14
  TEMPLATE: '{{.TEMPLATE | default "resume"}}'
  GENERATOR: scripts/generate_resume.py
  OUTPUT_DIR: docs

tasks:
  default:
    desc: Show available tasks
    silent: true
    cmds: [task --list]

  setup:
    desc: Install Python dependencies
    cmds:
      # create virtual environment if not exists
      - |
        if [ ! -d ".venv" ]; then
          echo "Creating virtual environment..."
          python3.14 -m venv .venv
        else
          echo "Virtual environment already exists."
        fi
        . .venv/bin/activate && 
        pip install --upgrade pip &&
        pip install -r requirements.txt
      - echo "Dependencies installed!"

  setup-output:
    desc: Ensure output directory exists
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
    silent: true

  generate:
    desc: Generate all formats
    deps: [setup-output]
    cmds:
      - "python {{.GENERATOR}} --template {{.TEMPLATE}} --format all"

  pdf:
    desc: Generate PDF using pandoc
    deps: [setup-output]
    silent: true
    cmds:
      - "pandoc ./docs/index.html -o ./docs/resume.pdf --include-in-header=./templates/styles.latex --pdf-engine=pdflatex"

  preview:
    desc: Start preview server for HTML files
    cmds:
      - "{{.PYTHON}} scripts/preview_server.py"

  all:
    desc: Complete workflow
    deps: [setup]
    silent: true
    cmds:
      - task: generate
      - task: pdf
      - task: preview
      - echo "Resume generation complete!"